In [1]:
# Data Analysis using Numpy

# part of py data ecosystem

# Start with Numpy Arrays


lis = [1,2,3]

In [2]:
lis


[1, 2, 3]

In [3]:
import numpy as np

# create an array from list

arr = np.array(lis)

In [4]:
arr  # one dimensional array

array([1, 2, 3])

In [5]:
# how to create multi dimensional arrays or matrix

mat = [[1,2,3],[4,5,6],[7,8,9]]

np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# use numpy built in methods for creating arrays

np.arange(0,10,1) #start, stop and step size

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# get even # arrays

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# genrate array of all zeros

np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# arrays of ones

np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# linspace

np.linspace(0,11,10) # last digit gives evenly spaced points between start and stop

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [14]:
# Create an identity matrix

np.eye(4) # it only takes single digit as an argument

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# using random method
np.random.rand(5)

array([0.46877812, 0.54975554, 0.61378994, 0.82685879, 0.92421989])

In [16]:
np.random.rand(5, 5) # note no need to pass a tuple

array([[0.5107652 , 0.00607397, 0.95417168, 0.5653691 , 0.34370301],
       [0.94723495, 0.44368277, 0.60892547, 0.06492963, 0.44485282],
       [0.64408688, 0.499693  , 0.98321561, 0.29749327, 0.07695883],
       [0.25373022, 0.9851191 , 0.10839424, 0.31975743, 0.29367312],
       [0.67657384, 0.31547766, 0.96737025, 0.74685586, 0.46989259]])

In [19]:
np.random.randint(1,11,10)

array([ 3,  5,  4,  5,  3,  9,  7,  7,  2, 10])

In [26]:
a = np.arange(20)

In [22]:
ra = np.random.randint(0,20,10)

In [27]:
# use reshape 

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
ra

array([18, 15,  8,  6,  2, 13, 12,  7, 18,  7])

In [30]:
# find max and min values 

ra.max()

18

In [31]:
ra.min()

2

In [32]:
# find loaction

ra.argmax()

0

In [34]:
ra.argmin()

4

In [35]:
ra.shape # indicates the shape


(10,)

In [36]:
ra = ra.reshape(2,5)

In [37]:
ra

array([[18, 15,  8,  6,  2],
       [13, 12,  7, 18,  7]])

In [38]:
ra.shape

(2, 5)

In [40]:
# find the datatypes in the array

ra.dtype

dtype('int32')

In [41]:
# Numpy Indexing 

arry = np.arange(0,21)

In [42]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [43]:
# similar to list use index slicing

arry[6]

6

In [44]:
# get values in a range

arry[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
arry[:11] # gives everything upto index -1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arry[6:] # start at an index to the end

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
arry[0:6] = 50 # change values in an array

In [48]:
arry


array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [50]:
# create array slices

slice_arry =arry[0:5]

In [51]:
slice_arry

array([50, 50, 50, 50, 50])

In [52]:
# changing values in slice modifies the original array, numpy does not set a copy
slice_arry[0:4] = 75


In [53]:
slice_arry

array([75, 75, 75, 75, 50])

In [54]:
arry # first 4 values are 75 now

array([75, 75, 75, 75, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [55]:
# how to create copies

arry_copy = arry.copy()

In [56]:
arry_copy

array([75, 75, 75, 75, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [57]:
arry_copy[:] = 99

In [58]:
arry_copy 

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99])

In [59]:
arry # array values dont change but copy array changed

array([75, 75, 75, 75, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [61]:
# create a matrix and indexing on matrix or 2d arrays

mat_arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [62]:
mat_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [63]:
mat_arr[0][1] # get a specific element

20

In [64]:
# get an entire row
mat_arr[1]


array([40, 50, 60])

In [65]:
# you can also use single bracket notation

#mat_arr[0][1] can be written as 

mat_arr[0,1]

20

In [66]:
mat_arr[:2,1:] # grab multiple rows or columns

array([[20, 30],
       [50, 60]])

In [67]:
mat_arr[1:]

array([[40, 50, 60],
       [70, 80, 90]])

In [68]:
arr = np.arange(1,21)

In [69]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [72]:
# use comparison  to get boolean arrays

bool_arr = arr> 5



In [73]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [74]:
# use conditional selection

arr[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [75]:
# we can also do it as

arr[arr> 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
arr[arr< 4]

array([1, 2, 3])

In [78]:
mat_arr = np.arange(50).reshape(5,10)

In [79]:
mat_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
mat_arr[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [84]:
# Basic operations on Numpy arrays

# Array with Array operations

arry = np.arange(0,21)


In [85]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [86]:
# add 2 arrays
arry + arry

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [87]:
# Subtract 
arry - arry

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
# multiply

arry * arry

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [89]:
# perform scalar operations

arry + 250

array([250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262,
       263, 264, 265, 266, 267, 268, 269, 270])

In [90]:
arry/2


array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [91]:
arry ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [92]:
# universal array functions

# some of the common functions

np.sqrt(arry)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [93]:
np.exp(arry)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [94]:
np.max(arry)

20

In [95]:
np.sin(arry)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525])

In [96]:
np.log(arry)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

# Excercise Section

#Import NumPy as np



In [97]:
import numpy as np

In [98]:
#Create an array of 10 zeros

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
#Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [111]:
#Create an array of 10 fives

arr = np.ones(10) * 5

In [112]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [113]:
#Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [114]:
#Create an array of all the even integers from 10 to 50
np.arange(10,51,2)


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [115]:
#Create a 3x3 matrix with values ranging from 0 to 8

np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
#Create a 3x3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
# Use NumPy to generate a random number between 0 and 1

np.random.rand(1)

array([0.377118])

In [120]:
# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

np.random.randn(25)

array([-0.1021212 , -0.21523515, -2.29634657,  0.13285189,  1.35233706,
       -0.97424401,  0.95331279, -0.47066839,  0.18105038,  0.45890769,
        2.50441732,  0.5721582 , -0.10659904, -0.22788539,  1.45160159,
       -0.1555414 , -0.07625191, -0.05497472,  0.34396377,  0.90092683,
       -1.45208908, -1.59607009, -0.81326016, -1.49097002, -0.66578924])

In [121]:
np.arange(0,1, 0.01).reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [123]:
#Create an array of 20 linearly spaced points between 0 and 1

np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [124]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [126]:
# get a specific output using indexing

mat[2: , 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [135]:
mat[3,4]

20

In [138]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [140]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [141]:
# sum of all values in the array

mat.sum()

325

In [142]:
# Get the standard deviation of the values in mat

np.std(mat)

7.211102550927978

In [147]:
# Get the sum of all the columns in mat

mat.sum(axis = 0)

array([55, 60, 65, 70, 75])